name: CI Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: oracle

      - name: Build Application
        run: |
          chmod +x ./gradlew
          ./gradlew build
          
          LINT_RESULTS=$(cat app/build/reports/lint-results-offlineDebug.txt)
          echo "## Lint Results" >> $GITHUB_STEP_SUMMARY
          echo "$LINT_RESULTS" >> $GITHUB_STEP_SUMMARY

      - name: Upload Unsigned APK (Offline)
        uses: actions/upload-artifact@v4
        with:
          name: arkreader-offline-${{ github.sha }}
          path: app/build/outputs/apk/offline/release/app-offline-release-unsigned.apk

      - name: Upload Unsigned APK (Online)
        uses: actions/upload-artifact@v4
        with:
          name: arkreader-online-${{ github.sha }}
          path: app/build/outputs/apk/online/release/app-online-release-unsigned.apk
